### ISSUE TITLE
 The tab order should always be from top to bottom (concerning toolbar and part)

### ISSUE THREAD

**Issue by ckeimel** [eclipse-efx/efxclipse-rt#250] opened 2018-10-23 12:32 UTC
Currently the tab order moves through the part first and then continues to the toolbar. Since the toolbar is on top of the part this feels very wierd. If the toolbar is on top the tab should into the toolbar first and then to the part.

**Comment by martinbluehweis** [comment] 2018-11-05 08:48
duplicate of #140

**Closed by martinbluehweis** 2018-11-05 08:48 UTC
